### ISSUE TITLE
what R version should I use?

### ISSUE THREAD

**Issue by Silverfoxcome** [michaelgruenstaeudl/PACVr#1]
Hi!!!!
Thank you so much for this beautiful tool to plot the coverage along the chloroplast genome assembly!!!!!
I wanted to try it as soon as I saw it!
I have had a few issues tough. Please, sorry for the bother :)
I was wondering with what R version should I work?
I was working with R version 3.4 but R told me that devtools required a more updated version.
I then installed R versión 3.6 and now the error message says:

> > install_github("michaelgruenstaeudl/PACVr")
> Downloading GitHub repo michaelgruenstaeudl/PACVr@master
> Skipping 2 packages not available: genbankr, BiocGenerics
> Installing 5 packages: RCircos, optparse, genbankr, BiocGenerics, getopt
> Installing packages into ‘/home/koalaz/R/x86_64-pc-linux-gnu-library/3.6’
> (as ‘lib’ is unspecified)
> Error: Failed to install 'PACVr' from GitHub:
>   (converted from warning) packages ‘genbankr’, ‘BiocGenerics’ are not available (for R version 3.6.1)

So, I was wondering what R version should I use??
In advance, thank you so much for your help :)

**Comment by Silverfoxcome** [comment]
I solved this issue already :D

**Comment by nilsj9** [comment]
Installation of the package "genbankr"  via 
``
BiocManager::install("genbankr")
``
before installing "PACVr" should fix this issue.
