### ISSUE TITLE
Importing a GBK file to create a TxDb object.

### ISSUE THREAD

**Issue by DelaFuenteJavier** [michaelgruenstaeudl/PACVr#6]
Hi everyone,
I am trying to import a GBK in order to create a TxDb object.
The file I want to import is this one (note that I changed the extension to .txt to be able to upload it here):

[myfile.txt](https://github.com/michaelgruenstaeudl/PACVr/files/5040089/myfile.txt)

As I have been recommended I tried to do it in the following  way:

```
gbkFile <- "path/to/my/file.gbk"

gb <- genbankr::readGenBank(gbkFile)

tx <- genbankr::makeTxDbFromGenBank(gb)
```

However this error shows up:

_Error in genbankr::readGenBank(gbkFile) :
file does not appear to an existing file or a GBAccession object. Valid file or text argument is required._

Reading other posts I think that the problem might be in the GBK file.

Thanks in advance!

**Comment by nilsj9** [comment]
Hi @deLFH as the error message indicates, your file cannot be located. Additionally, your file is missing a "source" feature which is mandatory. See our example: [example.gb]( https://github.com/michaelgruenstaeudl/PACVr/blob/master/inst/extdata/NC_045072/NC_045072.gb).
